# Project: Progetto
# Makefile created by Dev-C++ 5.3.0.4

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = automobile.o coda.o main.o menu.o rotonda.o strada.o utils.o $(RES)
LINKOBJ  = automobile.o coda.o main.o menu.o rotonda.o strada.o utils.o $(RES)
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
BIN      = Progetto.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

automobile.o: automobile.c
	$(CC) -c automobile.c -o automobile.o $(CFLAGS)

coda.o: coda.c
	$(CC) -c coda.c -o coda.o $(CFLAGS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

menu.o: menu.c
	$(CC) -c menu.c -o menu.o $(CFLAGS)

rotonda.o: rotonda.c
	$(CC) -c rotonda.c -o rotonda.o $(CFLAGS)

strada.o: strada.c
	$(CC) -c strada.c -o strada.o $(CFLAGS)

utils.o: utils.c
	$(CC) -c utils.c -o utils.o $(CFLAGS)
